# Generated by Django 5.2.4 on 2025-07-14 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount paid", max_digits=10
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(help_text="Date the payment was made"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional comment (e.g., for what month)"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Group payment is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
    ]
