# Generated by Django 5.2.4 on 2025-07-14 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="receiver",
            field=models.ForeignKey(
                help_text="Teacher or Admin who received the payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                help_text="Student who made the payment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="core.student",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date"], name="finance_pay_payment_72f761_idx"
            ),
        ),
    ]
