# Generated by Django 5.2.4 on 2025-07-14 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_holiday_alter_student_options_groupscheduleoverride"),
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="archived_time",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="group",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="is_archived",
        ),
        migrations.AddField(
            model_name="payment",
            name="student_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Group payment is associated with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.studentgroup",
            ),
        ),
    ]
