# Generated by Django 5.2.4 on 2025-07-14 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_group_price"),
        ("finance", "0003_remove_payment_archived_time_remove_payment_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="Month of the cheque (e.g., 2025-07-01 means July 2025)"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount billed for this month",
                        max_digits=10,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional note or adjustment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_group",
                    models.ForeignKey(
                        help_text="Student's course enrollment for which this bill is generated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cheques",
                        to="core.studentgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cheque",
                "verbose_name_plural": "Cheques",
                "ordering": ["-month"],
                "indexes": [
                    models.Index(fields=["month"], name="finance_che_month_0b7ce6_idx")
                ],
                "unique_together": {("student_group", "month")},
            },
        ),
        migrations.CreateModel(
            name="GroupPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the course starting from this date",
                        max_digits=10,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Date from which this price becomes active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group for which this price applies",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="core.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Price",
                "verbose_name_plural": "Group Prices",
                "ordering": ["-start_date"],
                "unique_together": {("group", "start_date")},
            },
        ),
    ]
