# Generated by Django 5.2.4 on 2025-07-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_cheque_groupprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupprice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
