# Generated by Django 5.2.4 on 2025-07-26 14:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_student_branch"),
        ("finance", "0005_groupprice_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="To'lov turi nomi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "To'lov Turi",
                "verbose_name_plural": "To'lov Turlari",
            },
        ),
        migrations.RemoveField(
            model_name="payment",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="student",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="student_group",
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEBIT", "Debit (Qarz)"),
                            ("CREDIT", "Credit (To'lov)"),
                        ],
                        max_length=6,
                        verbose_name="Tranzaksiya turi",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MONTHLY_FEE", "Oylik to'lov"),
                            ("INITIAL_FEE", "Boshlang'ich to'lov"),
                            ("BOOK_FEE", "Kitob uchun"),
                            ("PAYMENT", "To'lov"),
                            ("DISCOUNT", "Chegirma"),
                            ("BONUS", "Bonus"),
                            ("REFUND", "Pulni qaytarish"),
                        ],
                        max_length=20,
                        verbose_name="Kategoriya",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Always a positive value.",
                        max_digits=12,
                        verbose_name="Summa",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Izoh")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim tomonidan yaratildi",
                    ),
                ),
                (
                    "payment_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.paymenttype",
                        verbose_name="To'lov turi",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qabul qiluvchi",
                    ),
                ),
                (
                    "student_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="core.studentgroup",
                        verbose_name="O'quvchi guruhi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tranzaksiya",
                "verbose_name_plural": "Tranzaksiyalar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Cheque",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
