# Generated by Django 5.2.4 on 2025-07-31 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_paymenttype_remove_payment_receiver_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupprice",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Kurs narxi",
                "verbose_name_plural": "Kurs narxlari",
            },
        ),
    ]
