# Generated by Django 5.2.4 on 2025-08-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_alter_groupprice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="O'zgartirish kiritilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("MONTHLY_FEE", "Oylik to'lov"),
                    ("PAYMENT", "To'lov"),
                    ("DISCOUNT", "Chegirma"),
                    ("BONUS", "Bonus"),
                    ("REFUND", "Pulni qaytarish"),
                    ("OTHER_FEE", "Boshqa to'lovlar uchun"),
                ],
                max_length=20,
                verbose_name="Kategoriya",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
    ]
