# Generated by Django 5.2.4 on 2025-08-08 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_attendance_core_attend_student_e81481_idx_and_more"),
        ("finance", "0008_transaction_updated_at_alter_transaction_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["student_group", "category", "created_at"],
                name="finance_tra_student_966472_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["created_at"], name="finance_tra_created_ef4f06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["category"], name="finance_tra_categor_afb10f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type"], name="finance_tra_transac_2a23c2_idx"
            ),
        ),
    ]
