# Generated by Django 5.2.4 on 2025-07-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.BigIntegerField(
                db_index=True,
                help_text="Phone number without country code, e.g., 998901234567",
                unique=True,
            ),
        ),
    ]
