# Generated by Django 5.2.4 on 2025-07-15 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_loginlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_staff",
            new_name="is_ceo",
        ),
        migrations.AddField(
            model_name="user",
            name="enrollment_date",
            field=models.DateField(
                blank=True, help_text="Date the staff started working", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.BigIntegerField(
                db_index=True,
                help_text="Phone number without country code, e.g., 998901234567",
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        100000000000, message="Telefon raqami 12 xonali bo'lishi kerak."
                    ),
                    django.core.validators.MaxValueValidator(
                        999999999999, message="Telefon raqami 12 xonali bo'lishi kerak."
                    ),
                    django.core.validators.RegexValidator(
                        code="invalid_country_code",
                        message="Telefon raqami '998' bilan boshlanishi kerak.",
                        regex="^998",
                    ),
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
