# Generated by Django 5.2.4 on 2025-07-14 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="teacher",
            field=models.ForeignKey(
                help_text="Assigned teacher",
                limit_choices_to={"staff_info__is_teacher": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="branch",
            field=models.ForeignKey(
                help_text="Branch this room belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="room",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned classroom",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.room",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.branch"
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parents",
                to="core.student",
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="group",
            field=models.ForeignKey(
                help_text="Group the student is enrolled in",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="core.group",
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="student",
            field=models.ForeignKey(
                help_text="Student enrolled in this group",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_memberships",
                to="core.student",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="student_group",
            field=models.ForeignKey(
                help_text="Student attendance record",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="core.studentgroup",
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["name"], name="core_room_name_333d5c_idx"),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["name"], name="core_group_name_9ccf81_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["full_name"], name="core_studen_full_na_d1f1c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["phone_number"], name="core_studen_phone_n_9fbff1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["full_name"], name="core_parent_full_na_a9c322_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["phone_number"], name="core_parent_phone_n_f18aa4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentgroup",
            unique_together={("student", "group")},
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["date"], name="core_attend_date_801bf5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student_group", "date")},
        ),
    ]
