# Generated by Django 5.2.4 on 2025-07-14 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "ordering": ["date"],
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
        migrations.CreateModel(
            name="GroupScheduleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_date",
                    models.DateField(
                        blank=True,
                        help_text="Original lesson date (blank if extra lesson)",
                        null=True,
                    ),
                ),
                (
                    "new_date",
                    models.DateField(
                        blank=True,
                        help_text="New date if rescheduled or extra lesson",
                        null=True,
                    ),
                ),
                (
                    "new_start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Optional start time for rescheduled/extra lesson",
                        null=True,
                    ),
                ),
                (
                    "new_end_time",
                    models.TimeField(
                        blank=True,
                        help_text="Optional end time for rescheduled/extra lesson",
                        null=True,
                    ),
                ),
                ("is_cancelled", models.BooleanField(default=False)),
                ("is_extra", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group this override applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_overrides",
                        to="core.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Override",
                "verbose_name_plural": "Schedule Overrides",
                "indexes": [
                    models.Index(
                        fields=["original_date"], name="core_groups_origina_6d883f_idx"
                    ),
                    models.Index(
                        fields=["new_date"], name="core_groups_new_dat_5af303_idx"
                    ),
                ],
            },
        ),
    ]
