# Generated by Django 5.2.4 on 2025-07-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_holiday_alter_student_options_groupscheduleoverride"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="price",
        ),
    ]
