# Generated by Django 5.2.4 on 2025-07-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_group_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentgroup",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Custom price for this student (leave blank to use group price)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
