# Generated by Django 5.2.4 on 2025-07-15 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_studentgroup_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="teacher",
            field=models.ForeignKey(
                help_text="Assigned teacher",
                limit_choices_to={"is_teacher": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
