# Generated by Django 5.2.4 on 2025-07-26 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_group_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="core.branch",
            ),
        ),
    ]
