# Generated by Django 5.2.4 on 2025-08-08 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_student_branch"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"verbose_name": "Davomat", "verbose_name_plural": "Davomatlar"},
        ),
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name": "Flial", "verbose_name_plural": "Fliallar"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Guruh", "verbose_name_plural": "Guruhlar"},
        ),
        migrations.AlterModelOptions(
            name="holiday",
            options={
                "ordering": ["date"],
                "verbose_name": "Bayram",
                "verbose_name_plural": "Bayramlar",
            },
        ),
        migrations.AlterModelOptions(
            name="parent",
            options={"verbose_name": "Ota-ona", "verbose_name_plural": "Ota-onalar"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Xona", "verbose_name_plural": "Xonalar"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "O'quvchi", "verbose_name_plural": "O'quvchilar"},
        ),
        migrations.AlterField(
            model_name="group",
            name="branch",
            field=models.ForeignKey(
                help_text="Branch where the group is taught",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="core.branch",
            ),
        ),
    ]
