# Generated by Django 5.2.4 on 2025-08-08 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_attendance_options_alter_branch_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student_group"], name="core_attend_student_e81481_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student_group", "date"], name="core_attend_student_d539de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["teacher"], name="core_group_teacher_d5f2f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["branch"], name="core_group_branch__6fbc55_idx"),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["start_date"], name="core_group_start_d_54efeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["end_date"], name="core_group_end_dat_af8f94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupscheduleoverride",
            index=models.Index(
                fields=["group", "original_date"], name="core_groups_group_i_31c500_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupscheduleoverride",
            index=models.Index(
                fields=["group", "new_date"], name="core_groups_group_i_1a617a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["student"], name="core_parent_student_f7754f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["branch"], name="core_studen_branch__2a1cf8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentgroup",
            index=models.Index(fields=["group"], name="core_studen_group_i_a6ca18_idx"),
        ),
        migrations.AddIndex(
            model_name="studentgroup",
            index=models.Index(
                fields=["student"], name="core_studen_student_7adadc_idx"
            ),
        ),
    ]
